#!/usr/bin/env bash
set -euo pipefail

# N1PWN_ENV_LOADER
# Load keys from .env if present (do NOT commit .env)
if [[ -f ".env" ]]; then
  # shellcheck disable=SC1091
  source ".env"
fi
redact(){ echo "[REDACTED]"; }

# N1PWN_SECRET_OUTPUT_GUARD
# By default, do NOT print secrets to stdout (portfolio-safe).
# Set ALLOW_SECRET_OUTPUT=1 if you intentionally want raw values echoed.
ALLOW_SECRET_OUTPUT="${ALLOW_SECRET_OUTPUT:-0}"
emit_secret(){
  local v="$1"
  if [[ "$ALLOW_SECRET_OUTPUT" == "1" ]]; then
    printf '%s' "$v"
  else
    printf '%s' "[REDACTED]"
  fi
}


#
# N1PWN OSINT Key Management System
# Central config → Recon-ng, theHarvester, Amass
#
# Usage:
#   ./n1pwn-osint-bootstrap.sh [config-file]
#
# Default config:
#   $HOME/.config/n1pwn/osint-keys.conf

set -euo pipefail

CONFIG_FILE="${1:-$HOME/.config/n1pwn/osint-keys.conf}"

echo "[*] N1PWN OSINT Key Bootstrap"
echo "[*] Using config: $CONFIG_FILE"
echo

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[!] Config file not found: $CONFIG_FILE"
    echo
    echo "Create it with lines like:"
    echo "  shodan=SHODAN_API_KEY"
    echo "  virustotal=VT_API_KEY"
    echo "  bing=BING_API_KEY"
    echo "  github=GITHUB_TOKEN"
    echo "  hunter=HUNTER_IO_KEY"
    echo "  otx=OTX_API_KEY"
    echo "  censys_uid=CENSYS_UID"
    echo "  censys_secret=CENSYS_SECRET"
    echo "  securitytrails=SECURITYTRAILS_API_KEY"
    exit 1
fi

# ---------- Parse config ----------
SHODAN_KEY=""
VT_KEY=""
BING_KEY=""
GITHUB_KEY=""
HUNTER_KEY=""
OTX_KEY=""
CENSYS_UID=""
CENSYS_SECRET=""
SECURITYTRAILS_KEY=""

while IFS= read -r line; do
    # trim
    line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    # skip blanks and comments
    [ -z "$line" ] && continue
    [[ "$line" == \#* ]] && continue

    if [[ "$line" == *"="* ]]; then
        name="${line%%=*}"
        value="${line#*=}"
    elif [[ "$line" == *":"* ]]; then
        name="${line%%:*}"
        value="${line#*:}"
    else
        echo "[!] Skipping unrecognized line: $line"
        continue
    fi

    name="$(echo "$name" | tr '[:upper:]' '[:lower:]' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    value="$(echo "$value"         | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

    [ -z "$value" ] && continue

    case "$name" in
        shodan)           SHODAN_KEY="$value" ;;
        virustotal|vt)    VT_KEY="$value" ;;
        bing)             BING_KEY="$value" ;;
        github)           GITHUB_KEY="$value" ;;
        hunter|hunterio)  HUNTER_KEY="$value" ;;
        otx)              OTX_KEY="$value" ;;
        censys_uid)       CENSYS_UID="$value" ;;
        censys_secret)    CENSYS_SECRET="$value" ;;
        securitytrails)   SECURITYTRAILS_KEY="$value" ;;
        *)
            echo "[!] Unknown key name '$name' – ignoring."
            ;;
    esac
done < "$CONFIG_FILE"

# Helper: check if we have at least one key
have_any_key() {
    [ -n "$SHODAN_KEY" ] || \
    [ -n "$VT_KEY" ] || \
    [ -n "$BING_KEY" ] || \
    [ -n "$GITHUB_KEY" ] || \
    [ -n "$HUNTER_KEY" ] || \
    [ -n "$OTX_KEY" ] || \
    [ -n "$CENSYS_UID" ] || \
    [ -n "$SECURITYTRAILS_KEY" ]
}

# ---------- Recon-ng ----------
setup_reconng() {
    if ! command -v recon-ng >/dev/null 2>&1; then
        echo "[*] recon-ng not found in PATH – skipping Recon-ng."
        return
    fi

    if ! have_any_key; then
        echo "[*] No keys defined – skipping Recon-ng keys import."
        return
    fi

    local rc_dir="$HOME/tools/recon-ng"
    local rc_file="$rc_dir/keys.rc"

    mkdir -p "$rc_dir"

    echo "[*] Writing Recon-ng keys RC file: $rc_file"

    {
        echo "# Auto-generated by N1PWN OSINT Bootstrap"
        [ -n "$SHODAN_KEY" ]        && echo "keys add shodan_api $SHODAN_KEY"
        [ -n "$VT_KEY" ]            && echo "keys add virustotal_api $VT_KEY"
        [ -n "$BING_KEY" ]          && echo "keys add bing_api $BING_KEY"
        [ -n "$GITHUB_KEY" ]        && echo "keys add github_api $GITHUB_KEY"
        [ -n "$HUNTER_KEY" ]        && echo "keys add hunterio_api $HUNTER_KEY"
        [ -n "$OTX_KEY" ]           && echo "keys add otx_api $OTX_KEY"
        [ -n "$CENSYS_UID" ]        && echo "keys add censysio_uid $CENSYS_UID"
        echo "keys add censysio_secret $(redact)"
        [ -n "$SECURITYTRAILS_KEY" ]&& echo "keys add securitytrails_api $SECURITYTRAILS_KEY"
    } > "$rc_file"

    echo "[*] Importing keys into Recon-ng..."
    recon-ng -r "$rc_file" || {
        echo "[!] Recon-ng key import failed – run recon-ng manually and check."
        return
    }

    echo "[+] Recon-ng keys updated."
}

# ---------- theHarvester ----------
setup_theharvester() {
    if ! command -v theHarvester >/dev/null 2>&1; then
        echo "[*] theHarvester not found in PATH – skipping."
        return
    fi

    if ! have_any_key; then
        echo "[*] No keys defined – skipping theHarvester config."
        return
    fi

    local cfg_dir="$HOME/.config/theHarvester"
    local yaml="$cfg_dir/api-keys.yaml"

    mkdir -p "$cfg_dir"

    echo "[*] Writing theHarvester API key YAML: $yaml"

    {
        echo "# Auto-generated by N1PWN OSINT Bootstrap"
        echo "# Do NOT commit this file to version control."
        echo

        [ -n "$BING_KEY" ] && {
            echo "bing:"
            echo "  key: \"$BING_KEY\""
            echo
        }

        [ -n "$SHODAN_KEY" ] && {
            echo "shodan:"
            echo "  key: \"$SHODAN_KEY\""
            echo
        }

        [ -n "$VT_KEY" ] && {
            echo "virustotal:"
            echo "  key: \"$VT_KEY\""
            echo
        }

        [ -n "$OTX_KEY" ] && {
            echo "otx:"
            echo "  key: \"$OTX_KEY\""
            echo
        }

        [ -n "$HUNTER_KEY" ] && {
            echo "hunter:"
            echo "  key: \"$HUNTER_KEY\""
            echo
        }

        [ -n "$GITHUB_KEY" ] && {
            echo "github:"
            echo "  key: \"$GITHUB_KEY\""
            echo
        }

        [ -n "$ONYPHE_KEY" ] && {
            echo "onyphe:"
            echo "  key: \"$ONYPHE_KEY\""
            echo
        }

        if [ -n "$CENSYS_UID" ] && [ -n "$CENSYS_SECRET" ]; then
            echo "censys:"
            echo "  uid: \"$CENSYS_UID\""
            echo "  secret: $(emit_secret "$CENSYS_SECRET")"
            echo
        fi
    } > "$yaml"

    chmod 600 "$yaml"

    echo "[+] theHarvester API keys written to $yaml"
}

# ---------- Amass ----------
setup_amass() {
    if ! command -v amass >/dev/null 2>&1; then
        echo "[*] amass not found in PATH – skipping."
        return
    fi

    if ! have_any_key; then
        echo "[*] No keys defined – skipping Amass."
        return
    fi

    local cfg_dir="$HOME/.config/amass"
    local config_yaml="$cfg_dir/config.yaml"
    local datasources_yaml="$cfg_dir/datasources.yaml"

    mkdir -p "$cfg_dir"

    echo "[*] Writing Amass datasources.yaml: $datasources_yaml"

    {
        echo "# Auto-generated by N1PWN OSINT Bootstrap"
        echo "datasources:"

        [ -n "$SHODAN_KEY" ] && {
            echo "  - name: Shodan"
            echo "    creds:"
            echo "      account:"
            echo "        apikey: $(emit_secret "$SHODAN_KEY")"
        }

        [ -n "$VT_KEY" ] && {
            echo "  - name: VirusTotal"
            echo "    creds:"
            echo "      account:"
            echo "        apikey: $(emit_secret "$VT_KEY")"
        }

        [ -n "$SECURITYTRAILS_KEY" ] && {
            echo "  - name: SecurityTrails"
            echo "    creds:"
            echo "      account:"
            echo "        apikey: $(emit_secret "$SECURITYTRAILS_KEY")"
        }

        if [ -n "$CENSYS_UID" ] && [ -n "$CENSYS_SECRET" ]; then
            echo "  - name: Censys"
            echo "    creds:"
            echo "      account:"
            echo "        apikey: $(emit_secret "$CENSYS_UID")"
            echo "        secret: $(emit_secret "$CENSYS_SECRET")"
        fi

    } > "$datasources_yaml"

    echo "[*] Ensuring Amass config.yaml exists and points to datasources.yaml"

    if [ ! -f "$config_yaml" ]; then
        {
            echo "# Auto-generated by N1PWN OSINT Bootstrap"
            echo "options:"
            echo "  datasources: \"$datasources_yaml\""
        } > "$config_yaml"
    fi

    chmod 600 "$datasources_yaml" "$config_yaml" || true

    echo "[+] Amass configuration updated in $cfg_dir"
}

# ---------- Run all ----------
setup_reconng
echo
setup_theharvester
echo
setup_amass
echo

echo "[+] N1PWN OSINT Bootstrap complete."
echo "[+] Source of truth: $CONFIG_FILE"
echo
